---------------------------------------------
-- Export file for user FRK                --
-- Created by jiangp on 2016/6/16, 9:21:26 --
---------------------------------------------

spool function.log

prompt
prompt Creating function GET_FUN_NAME
prompt ==============================
prompt
CREATE OR REPLACE FUNCTION GET_FUN_NAME(P_FUN_ID IN NUMBER) RETURN VARCHAR2 IS
  V_FUN_NAME VARCHAR2(64);
BEGIN
  SELECT FUN_NAME INTO V_FUN_NAME FROM SYS_FUN WHERE FUN_ID = P_FUN_ID;
  RETURN(V_FUN_NAME);
END GET_FUN_NAME;
/

prompt
prompt Creating function GET_ORG_INHERITEDNAME
prompt =======================================
prompt
CREATE OR REPLACE FUNCTION GET_ORG_INHERITEDNAME(P_ORG_ID IN NUMBER) RETURN VARCHAR2 IS
  V_ORG_INHERITEDNAME VARCHAR2(512);
BEGIN

  SELECT INHERITED_NAME INTO V_ORG_INHERITEDNAME FROM SYS_ORG WHERE ORG_ID = P_ORG_ID;

  RETURN(V_ORG_INHERITEDNAME);

END GET_ORG_INHERITEDNAME;
/

prompt
prompt Creating function GET_ORG_NAME
prompt ==============================
prompt
CREATE OR REPLACE FUNCTION GET_ORG_NAME(P_ORG_ID IN NUMBER) RETURN VARCHAR2 IS
  V_ORG_NAME VARCHAR2(64);
BEGIN

  SELECT ORG_NAME INTO V_ORG_NAME FROM SYS_ORG WHERE ORG_ID = P_ORG_ID;

  RETURN(V_ORG_NAME);

END GET_ORG_NAME;
/

prompt
prompt Creating function GET_ORG_PARENTNAME
prompt ====================================
prompt
CREATE OR REPLACE FUNCTION GET_ORG_PARENTNAME(P_PARENT_ID IN NUMBER) RETURN VARCHAR2 IS
  V_PARENT_NAME VARCHAR2(64);
BEGIN

  SELECT ORG_NAME INTO V_PARENT_NAME FROM SYS_ORG WHERE ORG_ID = P_PARENT_ID;

  RETURN(V_PARENT_NAME);

END GET_ORG_PARENTNAME;
/

prompt
prompt Creating function GET_REAL_NAME
prompt ===============================
prompt
CREATE OR REPLACE FUNCTION GET_REAL_NAME(P_USER_ID IN NUMBER) RETURN VARCHAR2 IS
  V_REAL_NAME VARCHAR2(64);
BEGIN

  SELECT REAL_NAME INTO V_REAL_NAME FROM SYS_USER WHERE USER_ID = P_USER_ID;

  RETURN(V_REAL_NAME);

END GET_REAL_NAME;
/

prompt
prompt Creating function GET_USERNAME
prompt ==============================
prompt
CREATE OR REPLACE FUNCTION GET_USERNAME(P_USER_ID IN NUMBER) RETURN VARCHAR2 IS
  V_USERNAME VARCHAR2(64);
BEGIN

  SELECT USERNAME INTO V_USERNAME FROM SYS_USER WHERE USER_ID = P_USER_ID;

  RETURN(V_USERNAME);

END GET_USERNAME;
/


spool off
