DROP TABLE IF EXISTS `SYS_BEHAVIOR_LOG`;
CREATE TABLE `SYS_BEHAVIOR_LOG`(  
  `BEHAVIOR_ID`       INT(8) NOT NULL AUTO_INCREMENT,
  `SESSION_ID`        VARCHAR(32) NOT NULL,
  `LOGGED_DATE`       TIMESTAMP NOT NULL,
  `ACTION`            VARCHAR(128),
  `DATA_CHANGED`      INT(1) NOT NULL,
  PRIMARY KEY (`BEHAVIOR_ID`)
) AUTO_INCREMENT=1 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_DATA_LOG`;
CREATE TABLE `SYS_DATA_LOG`(  
  `BEHAVIOR_ID`       INT(8) NOT NULL,
  `LOGGED_DATE`       TIMESTAMP NOT NULL,
  `TABLE_NAME`        VARCHAR(32) NOT NULL,
  `COLUMN_NAME`       VARCHAR(32) NOT NULL,
  `KEY_VALUE`         INT(8) NOT NULL,
  `OLD_VALUE`         VARCHAR(512),
  `NEW_VALUE`         VARCHAR(512)
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_DIC`;
CREATE TABLE `SYS_DIC`(  
  `DIC_ID`            INT(8) NOT NULL AUTO_INCREMENT,
  `DIC_NAME`          VARCHAR(64) NOT NULL,
  `DIC_KEY`           VARCHAR(32) NOT NULL,
  `DIC_VALUE`         VARCHAR(128) NOT NULL,
  `DIC_TYPE`          VARCHAR(32) NOT NULL,
  `DIC_SYMBOL`        VARCHAR(128),
  `CREATED_BY`        INT(8) NOT NULL,
  `CREATED_DATE`      TIMESTAMP NOT NULL,
  `LAST_UPDATED_BY`   INT(8) NOT NULL,
  `LAST_UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`DIC_ID`)
) AUTO_INCREMENT=1000 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_FUN`;
CREATE TABLE `SYS_FUN`(  
  `FUN_ID`            INT(8) NOT NULL AUTO_INCREMENT,
  `FUN_NAME`          VARCHAR(64) NOT NULL,
  `PARENT_ID`         INT(8) NOT NULL,
  `SORT_NUM`          INT(3) NOT NULL,
  `LEVEL_NUM`         INT(1) NOT NULL,
  `DELETED`           INT(1) NOT NULL,
  `CREATED_BY`        INT(8),
  `CREATED_DATE`      TIMESTAMP,
  `LAST_UPDATED_BY`   INT(8),
  `LAST_UPDATED_DATE` TIMESTAMP,
  PRIMARY KEY (`FUN_ID`)
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_FUN_URL`;
CREATE TABLE `SYS_FUN_URL`(  
  `FUN_ID`            INT(8) NOT NULL,
  `URL_ID`            INT(8) NOT NULL
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_LOGIN_LOG`;
CREATE TABLE `SYS_LOGIN_LOG`(  
  `SESSION_ID`        VARCHAR(32) NOT NULL,
  `USER_ID`           INT(8) NOT NULL,
  `USERNAME`          VARCHAR(32) NOT NULL,
  `REAL_NAME`         VARCHAR(32) NOT NULL,
  `IP`                VARCHAR(16) NOT NULL,
  `ORG_ID`            INT(8) NOT NULL,
  `ORG_NAME`          VARCHAR(64) NOT NULL,
  `INHERITED_NAME`    VARCHAR(512) NOT NULL,
  `LOGIN_DATE`        TIMESTAMP NOT NULL,
  `LOGOUT_DATE`       TIMESTAMP,
  `OS`                VARCHAR(32),
  `BROWSER`           VARCHAR(32),
  `USER_AGENT`        VARCHAR(256),
  PRIMARY KEY (`SESSION_ID`)
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_MENU`;
CREATE TABLE `SYS_MENU`(  
  `MENU_ID`           INT(8) NOT NULL AUTO_INCREMENT,
  `MENU_NAME`         VARCHAR(64) NOT NULL,
  `MENU_URL`          VARCHAR(64),
  `ICON`              VARCHAR(16),
  `PARENT_ID`         INT(8) NOT NULL,
  `FUN_ID`            INT(8) NOT NULL,
  `SORT_NUM`          INT(3) NOT NULL,
  `LEVEL_NUM`         INT(1) NOT NULL,
  `DELETED`           INT(1) NOT NULL,
  `CREATED_BY`        INT(8),
  `CREATED_DATE`      TIMESTAMP,
  `LAST_UPDATED_BY`   INT(8),
  `LAST_UPDATED_DATE` TIMESTAMP,
  PRIMARY KEY (`MENU_ID`)
) AUTO_INCREMENT=600 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_ORG`;
CREATE TABLE `SYS_ORG`(  
  `ORG_ID`            INT(8) NOT NULL AUTO_INCREMENT,
  `ORG_CODE`          VARCHAR(16) NOT NULL,
  `ORG_NAME`          VARCHAR(64) NOT NULL,
  `PARENT_ID`         INT(8) NOT NULL,
  `INHERITED_ID`      VARCHAR(128),
  `INHERITED_NAME`    VARCHAR(512) NOT NULL,
  `SORT_NUM`          INT(4) NOT NULL,
  `LEVEL_NUM`         INT(2) NOT NULL,
  `TEL`               VARCHAR(16),
  `ADDRESS`           VARCHAR(128),
  `REMARK`            VARCHAR(128),
  `DELETED`           INT(1) NOT NULL,
  `CREATED_BY`        INT(8) NOT NULL,
  `CREATED_DATE`      TIMESTAMP NOT NULL,
  `LAST_UPDATED_BY`   INT(8) NOT NULL,
  `LAST_UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ORG_ID`)
) AUTO_INCREMENT=10 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE`(  
  `ROLE_ID`           INT(8) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME`         VARCHAR(64) NOT NULL,
  `ROLE_TYPE`         INT(1) NOT NULL,
  `ORG_ID`            INT(8),
  `REMARK`            VARCHAR(128),
  `DELETED`           INT(1) NOT NULL,
  `CREATED_BY`        INT(8) NOT NULL,
  `CREATED_DATE`      TIMESTAMP NOT NULL,
  `LAST_UPDATED_BY`   INT(8) NOT NULL,
  `LAST_UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) AUTO_INCREMENT=100 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_ROLE_FUN`;
CREATE TABLE `SYS_ROLE_FUN`(  
  `ROLE_ID`           INT(8) NOT NULL,
  `FUN_ID`            INT(8) NOT NULL
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_ROLE_USER`;
CREATE TABLE `SYS_ROLE_USER`(  
  `ROLE_ID`           INT(8) NOT NULL,
  `USER_ID`           INT(8) NOT NULL
) ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_URL`;
CREATE TABLE `SYS_URL`(  
  `URL_ID`              INT(8) NOT NULL AUTO_INCREMENT,
  `URL_NAME`            VARCHAR(64),
  `URL_PATTERN`         VARCHAR(64) NOT NULL,
  `HTTP_METHOD`         VARCHAR(8) NOT NULL,
  `ACTION_CODE`         VARCHAR(32),
  `ARGS_CODE`           VARCHAR(64),
  `LOGGED_DATA_CHANGED` INT(1) NOT NULL,
  `CREATED_BY`          INT(8),
  `CREATED_DATE`        TIMESTAMP,
  `LAST_UPDATED_BY`     INT(8),
  `LAST_UPDATED_DATE`   TIMESTAMP,
  PRIMARY KEY (`URL_ID`)
) AUTO_INCREMENT=600 ENGINE=INNODB CHARSET=utf8;

DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER`(  
  `USER_ID`           INT(8) NOT NULL AUTO_INCREMENT,
  `USERNAME`          VARCHAR(32) NOT NULL,
  `REAL_NAME`         VARCHAR(64) NOT NULL,
  `PWD`               CHAR(32) NOT NULL,
  `ORG_ID`            INT(8) NOT NULL,
  `LOCKED`            INT(1) NOT NULL,
  `ERROR_TIME`        INT(2),
  `AGE`               INT(3),
  `BIRTHDAY`          TIMESTAMP,
  `PHONE`             VARCHAR(16),
  `MOBILE`            VARCHAR(16),
  `EMAIL`             VARCHAR(64),
  `ADDRESS`           VARCHAR(128),
  `REMARK`            VARCHAR(128),
  `USER_PIC_DATA`     BLOB,
  `USER_PIC_SUFFIX`   VARCHAR(16),
  `ABOUT`             TEXT,
  `LAST_LOGIN_DATE`   TIMESTAMP,
  `LAST_LOGIN_IP`     VARCHAR(16),
  `DELETED`           INT(1) NOT NULL,
  `CREATED_BY`        INT(8) NOT NULL,
  `CREATED_DATE`      TIMESTAMP NOT NULL,
  `LAST_UPDATED_BY`   INT(8) NOT NULL,
  `LAST_UPDATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `INDEX_SYS_USER` (`USERNAME`)
) AUTO_INCREMENT=1720 ENGINE=INNODB CHARSET=utf8;